#--------------
#	Example
# 	git clone code
# 	docker build -f Dockerfile.fluxbox-withWineHQ_focal -t docker-desktop:winhq-squeeze .
# 	docker run -p 80:80 -p 5900:5900 --name "UDesktop" --hostname "UDesktop" -it -d docker-desktop:winhq-squeeze
# 	NoVnc:
#		addr: http://127.0.0.1//vnc.html?path=websockify/?token=admin
#		password: admin
#--------------

FROM ubuntu:focal
ARG UbuntuVersion="focal"

ARG DEBIAN_FRONTEND noninteractive
ARG LC_ALL C.UTF-8
ARG LANG en_US.UTF-8
ARG LANGUAGE en_US.UTF-8

#--------------Timezone--------------
ARG TZ=Asia/Chongqing
#--------------apt mirrors--------------
ARG APT_MIRRORS="\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UbuntuVersion} main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UbuntuVersion}-updates main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UbuntuVersion}-backports main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${UbuntuVersion}-security main restricted universe multiverse\n\
"
#--------------apt pkg--------------
ARG APT_PKG_default="sudo wget tar nano xz-utils net-tools nano"
ARG APT_PKG_daemon="supervisor"
ARG APT_PKG_desktop="fluxbox lxterminal pcmanfm"
ARG APT_PKG_vnc="tightvncserver python3-pip"
ARG APT_PKG_lang="language-pack-en language-pack-en-base language-pack-zh-hans fonts-droid-fallback ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming"

ARG APT_PKG_ALL="\
$APT_PKG_default \
$APT_PKG_daemon \
$APT_PKG_desktop \
$APT_PKG_vnc \
$APT_PKG_lang \
"

# default user
ARG USER=admin
ARG USER_PASS=admin

# default store directory
ARG USER_HOME_DIR="/usr/local/$USER"
ARG APPS_DIR="$USER_HOME_DIR/apps"
ARG NoVNC_Token_Dir="$APPS_DIR/novnc/tokens.conf"

#--------------start VNC script--------------
ARG VncBasePort=5900
ARG StartVNC_CMD="#!/bin/sh\n\
rm -rf /tmp/.X11-unix/*\n\
rm -rf /tmp/.X*-lock\n\
killall tightvncserver\n\
DisplayResolution=1600x900\n\
DisplayDepth=24\n\
UserList=$(ls $NoVNC_Token_Dir)\n\
idx=0\n\
if [ -z \$UserList ]; then\n\
echo 'no user'\n\
exit\n\
fi\n\
\n\
for user in \$UserList;do\n\
	echo running user:\$user idx:\$idx;\n\
	sudo -u \$user -- tightvncserver :\$idx -geometry \$DisplayResolution -depth \$DisplayDepth -rfbport $(expr $VncBasePort + \$idx)\n\
	idx=$(expr \$idx + 1)\n\
done\n\
"

#--------------boot service--------------
ARG SupervisorConfig="\
[supervisord]\n\
nodaemon=true\n\
\n\
[program:VncServer]\n\
command=$APPS_DIR/startvnc\n\
autorestart=false\n\
stdout_logfile=/dev/fd/1\n\
stdout_logfile_maxbytes=0\n\
redirect_stderr=true\n\
\n\
[program:noVnc]\n\
command=$APPS_DIR/novnc/utils/websockify/run --token-plugin TokenFile --token-source $NoVNC_Token_Dir --web $APPS_DIR/novnc 80\n\
autorestart=false\n\
stdout_logfile=/dev/fd/1\n\
stdout_logfile_maxbytes=0\n\
redirect_stderr=true\n\
user=$USER\n\
"

#-------------- WineHQ Key
# ref:  https://dl.winehq.org/wine-builds/winehq.key
ARG WineKey="\
-----BEGIN PGP PUBLIC KEY BLOCK-----\n\
\n\
mQGNBFwOmrgBDAC9FZW3dFpew1hwDaqRfdQQ1ABcmOYu1NKZHwYjd+bGvcR2LRGe\n\
R5dfRqG1Uc/5r6CPCMvnWxFprymkqKEADn8eFn+aCnPx03HrhA+lNEbciPfTHylt\n\
NTTuRua7YpJIgEOjhXUbxXxnvF8fhUf5NJpJg6H6fPQARUW+5M//BlVgwn2jhzlW\n\
U+uwgeJthhiuTXkls9Yo3EoJzmkUih+ABZgvaiBpr7GZRw9GO1aucITct0YDNTVX\n\
KA6el78/udi5GZSCKT94yY9ArN4W6NiOFCLV7MU5d6qMjwGFhfg46NBv9nqpGinK\n\
3NDjqCevKouhtKl2J+nr3Ju3Spzuv6Iex7tsOqt+XdZCoY+8+dy3G5zbJwBYsMiS\n\
rTNF55PHtBH1S0QK5OoN2UR1ie/aURAyAFEMhTzvFB2B2v7C0IKIOmYMEG+DPMs9\n\
FQs/vZ1UnAQgWk02ZiPryoHfjFO80+XYMrdWN+RSo5q9ODClloaKXjqI/aWLGirm\n\
KXw2R8tz31go3NMAEQEAAbQnV2luZUhRIHBhY2thZ2VzIDx3aW5lLWRldmVsQHdp\n\
bmVocS5vcmc+iQHOBBMBCgA4AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAFiEE\n\
1D9kAUU2nFHXht3qdvGiD/mHZy8FAlwOmyUACgkQdvGiD/mHZy/zkwv7B+nKFlDY\n\
Bzz/7j0gqIODbs5FRZRtuf/IuPP3vZdWlNfAW/VyaLtVLJCM/mmaf/O6/gJ+D+E9\n\
BBoSmHdHzBBOQHIj5IbRedynNcHT5qXsdBeU2ZPR50sdE+jmukvw3Wa5JijoDgUu\n\
LGLGtU48Z3JsBXQ54OlnTZXQ2SMFhRUa10JANXSJQ+QY2Wo2Pi2+MEAHcrd71A2S\n\
0mT2DQSSBQ92c6WPfUpOSBawd8P0ipT7rVFNLJh8HVQGyEWxPl8ecDEHoVfG2rdV\n\
D0ADbNLx9031UUwpUicO6vW/2Ec7c3VNG1cpOtyNTw/lEgvsXOh3GQs/DvFvMy/h\n\
QzaeF3Qq6cAPlKuxieJe4lLYFBTmCAT4iB1J8oeFs4G7ScfZH4+4NBe3VGoeCD/M\n\
Wl+qxntAroblxiFuqtPJg+NKZYWBzkptJNhnrBxcBnRinGZLw2k/GR/qPMgsR2L4\n\
cP+OUuka+R2gp9oDVTZTyMowz+ROIxnEijF50pkj2VBFRB02rfiMp7q6iQIzBBAB\n\
CgAdFiEE2iNXmnTUrZr50/lFzvrI6q8XUZ0FAlwOm3AACgkQzvrI6q8XUZ3KKg/+\n\
MD8CgvLiHEX90fXQ23RZQRm2J21w3gxdIen/N8yJVIbK7NIgYhgWfGWsGQedtM7D\n\
hMwUlDSRb4rWy9vrXBaiZoF3+nK9AcLvPChkZz28U59Jft6/l0gVrykey/ERU7EV\n\
w1Ie1eRu0tRSXsKvMZyQH8897iHZ7uqoJgyk8U8CvSW+V80yqLB2M8Tk8ECZq34f\n\
HqUIGs4Wo0UZh0vV4+dEQHBh1BYpmmWl+UPf7nzNwFWXu/EpjVhkExRqTnkEJ+Ai\n\
OxbtrRn6ETKzpV4DjyifqQF639bMIem7DRRf+mkcrAXetvWkUkE76e3E9KLvETCZ\n\
l4SBfgqSZs2vNngmpX6Qnoh883aFo5ZgVN3v6uTS+LgTwMt/XlnDQ7+Zw+ehCZ2R\n\
CO21Y9Kbw6ZEWls/8srZdCQ2LxnyeyQeIzsLnqT/waGjQj35i4exzYeWpojVDb3r\n\
tvvOALYGVlSYqZXIALTx2/tHXKLHyrn1C0VgHRnl+hwv7U49f7RvfQXpx47YQN/C\n\
PWrpbG69wlKuJptr+olbyoKAWfl+UzoO8vLMo5njWQNAoAwh1H8aFUVNyhtbkRuq\n\
l0kpy1Cmcq8uo6taK9lvYp8jak7eV8lHSSiGUKTAovNTwfZG2JboGV4/qLDUKvpa\n\
lPp2xVpF9MzA8VlXTOzLpSyIVxZnPTpL+xR5P9WQjMS5AY0EXA6auAEMAMReKL89\n\
0z0SL+/i/geB/agfG/k6AXiG2a9kVWeIjAqFwHKl9W/DTNvOqCDgAt51oiHGRRjt\n\
1Xm3XZD4p+GM1uZWn9qIFL49Gt5x94TqdrsKTVCJr0Kazn2mKQc7aja0zac+WtZG\n\
OFn7KbniuAcwtC780cyikfmmExLI1/Vjg+NiMlMtZfpK6FIW+ulPiDQPdzIhVppx\n\
w9/KlR2Fvh4TbzDsUqkFQSSAFdQ65BWgvzLpZHdKO/ILpDkThLbipjtvbBv/pHKM\n\
O/NFTNoYkJ3cNW/kfcynwV+4AcKwdRz2A3Mez+g5TKFYPZROIbayOo01yTMLfz2p\n\
jcqki/t4PACtwFOhkAs+MYPPyZDUkTFcEJQCPDstkAgmJWI3K2qELtDOLQyps3WY\n\
Mfp+mntOdc8bKjFTMcCEk1zcm14K4Oms+w6dw2UnYsX1FAYYhPm8HUYwE4kP8M+D\n\
9HGLMjLqqF/kanlCFZs5Avx3mDSAx6zS8vtNdGh+64oDNk4x4A2j8GTUuQARAQAB\n\
iQG8BBgBCgAmFiEE1D9kAUU2nFHXht3qdvGiD/mHZy8FAlwOmrgCGwwFCQPCZwAA\n\
CgkQdvGiD/mHZy9FnAwAgfUkxsO53Pm2iaHhtF4+BUc8MNJj64Jvm1tghr6PBRtM\n\
hpbvvN8SSOFwYIsS+2BMsJ2ldox4zMYhuvBcgNUlix0G0Z7h1MjftDdsLFi1DNv2\n\
J9dJ9LdpWdiZbyg4Sy7WakIZ/VvH1Znd89Imo7kCScRdXTjIw2yCkotE5lK7A6Ns\n\
NbVuoYEN+dbGioF4csYehnjTdojwF/19mHFxrXkdDZ/V6ZYFIFxEsxL8FEuyI4+o\n\
LC3DFSA4+QAFdkjGFXqFPlaEJxWt5d7wk0y+tt68v+ulkJ900BvR+OOMqQURwrAi\n\
iP3I28aRrMjZYwyqHl8i/qyIv+WRakoDKV+wWteR5DmRAPHmX2vnlPlCmY8ysR6J\n\
2jUAfuDFVu4/qzJe6vw5tmPJMdfvy0W5oogX6sEdin5M5w2b3WrN8nXZcjbWymqP\n\
6jCdl6eoCCkKNOIbr/MMSkd2KqAqDVM5cnnlQ7q+AXzwNpj3RGJVoBxbS0nn9JWY\n\
QNQrWh9rAcMIGT+b1le0\n\
=4lsa\n\
-----END PGP PUBLIC KEY BLOCK-----\n\
\n\
"
ARG WineHQVersion="devel"

#--------------fluxbox file--------------
ARG FluxboxMenu="\
[begin] (fluxbox)\n\
[exec] (PCMan) {dbus-run-session pcmanfm} <>\n\
[exec] (Explorer) {/opt/wine-${WineHQVersion}/bin/wine /opt/wine-${WineHQVersion}/lib/wine/i386-windows/explorer.exe} <> \n\
[exec] (Terminal) { x-terminal-emulator -T "Bash" -e /bin/bash --login} <> \n\
[submenu] (System) {} \n\
[include] (/etc/X11/fluxbox/fluxbox-menu)\n\
[end]\n\
[end]\n\
"

#--------------noVNC Default Token--------------
ARG NoVncDefaultToken="\
$USER: 127.0.0.1:$VncBasePort\n\
"


#--------------Main run process--------------
RUN \
	echo "$APT_MIRRORS" > /etc/apt/sources.list&& \
	ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo "$TZ" > /etc/timezone &&\
			apt-get update && \
			apt-get -y install $APT_PKG_ALL && \
	useradd -m -d $USER_HOME_DIR -r $USER -p $(openssl passwd $USER_PASS) && \
	usermod -aG sudo $USER && \
	chsh -s /bin/bash $USER &&\
	mkdir $USER_HOME_DIR/.vnc &&\
	echo "#!/bin/sh\nfluxbox &" > $USER_HOME_DIR/.vnc/xstartup &&\
	chmod +x $USER_HOME_DIR/.vnc/xstartup &&\
	echo $USER_PASS | vncpasswd -f > $USER_HOME_DIR/.vnc/passwd && \
	chmod 0600 $USER_HOME_DIR/.vnc/passwd && \
	mkdir -p $USER_HOME_DIR/.fluxbox && echo $FluxboxMenu > $USER_HOME_DIR/.fluxbox/menu && \
			python3 -m pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple &&\
			mkdir -p $APPS_DIR &&\
			echo $StartVNC_CMD > $APPS_DIR/startvnc && chmod +x $APPS_DIR/startvnc &&\
			wget -O - https://ghproxy.com/https://github.com/novnc/websockify/archive/refs/tags/v0.11.0.tar.gz | tar -xzv -C $APPS_DIR && \
			wget -O - https://ghproxy.com/https://github.com/novnc/noVNC/archive/refs/tags/v1.4.0.tar.gz | tar -xzv -C $APPS_DIR && \
			mv $APPS_DIR/noVNC-1.4.0 $APPS_DIR/novnc && \
			ln -s $APPS_DIR/novnc/vnc_lite.html $APPS_DIR/novnc/index.html &&\
			mv $APPS_DIR/websockify-0.11.0 $APPS_DIR/novnc/utils/websockify  &&\
			mkdir -p $NoVNC_Token_Dir &&\
			echo $NoVncDefaultToken > $NoVNC_Token_Dir/$USER && \
	mkdir -p /var/lib/locales/supported.d&&\
	echo "LC_ALL=C.UTF-8\nLANG=en_US.UTF-8\nLANGUAGE=en_US.UTF-8" >> /etc/environment &&\
	locale-gen && \
			apt-get -y install gnupg2 gnupg && \
			dpkg --add-architecture i386&&\
			echo "$WineKey" | apt-key add -  && \
			echo "deb https://mirrors.tuna.tsinghua.edu.cn/wine-builds/ubuntu/ ${UbuntuVersion} main" |tee /etc/apt/sources.list.d/winehq.list && \
			apt-get update && apt-get -y install --install-recommends winehq-${WineHQVersion} && \
			mkdir -p /opt/wine-${WineHQVersion}/share/wine/mono && wget -O - http://mirrors.ustc.edu.cn/wine/wine/wine-mono/8.0.0/wine-mono-8.0.0-x86.tar.xz | tar -xJv -C /opt/wine-${WineHQVersion}/share/wine/mono && \
			mkdir -p /opt/wine-${WineHQVersion}/share/wine/gecko && \
			wget -O /opt/wine-${WineHQVersion}/share/wine/gecko/wine-gecko-2.47.4-x86.msi http://mirrors.ustc.edu.cn/wine/wine/wine-gecko/2.47.4/wine-gecko-2.47.4-x86.msi && \
			wget -O /opt/wine-${WineHQVersion}/share/wine/gecko/wine-gecko-2.47.4-x86_64.msi http://mirrors.ustc.edu.cn/wine/wine/wine-gecko/2.47.4/wine-gecko-2.47.4-x86_64.msi && \
	echo $SupervisorConfig > /etc/supervisor/conf.d/supervisord.conf &&\
			chmod 740 $USER_HOME_DIR &&\
			chown -R $USER:$USER $USER_HOME_DIR &&\
	apt-get -y full-upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 5900
EXPOSE 80

CMD ["/usr/bin/supervisord"]
